// Commonly used emoji shortcodes that markdown-it-emoji recognizes.
// Format: { code: ':xxx:', char: '😀', name: 'searchable name' }
// Curated subset (~200) covering daily blogging needs.

export interface EmojiEntry {
  code: string
  char: string
  name: string
}

// Build entries from compact tuples to keep this file small.
const RAW: Array<[string, string, string]> = [
  // Smileys & people
  ['smile', '😄', '笑 happy'],
  ['smiley', '😃', '微笑'],
  ['grinning', '😀', '咧嘴笑'],
  ['blush', '😊', '害羞 blush'],
  ['laughing', '😆', '大笑 lol'],
  ['joy', '😂', '笑哭 joy'],
  ['rofl', '🤣', '笑翻 rofl'],
  ['wink', '😉', '眨眼'],
  ['heart_eyes', '😍', '爱心眼'],
  ['kissing_heart', '😘', '飞吻'],
  ['yum', '😋', '美味'],
  ['stuck_out_tongue', '😛', '吐舌'],
  ['stuck_out_tongue_winking_eye', '😜', '吐舌眨眼'],
  ['smirk', '😏', '坏笑 smirk'],
  ['relieved', '😌', '安心'],
  ['pensive', '😔', '沉思'],
  ['unamused', '😒', '不爽'],
  ['confused', '😕', '困惑'],
  ['thinking', '🤔', '思考 thinking'],
  ['neutral_face', '😐', '面无表情'],
  ['expressionless', '😑', '无语'],
  ['no_mouth', '😶', '无嘴'],
  ['hushed', '😯', '吃惊'],
  ['open_mouth', '😮', '张嘴'],
  ['astonished', '😲', '惊讶'],
  ['flushed', '😳', '脸红'],
  ['scream', '😱', '尖叫'],
  ['fearful', '😨', '害怕'],
  ['cold_sweat', '😰', '冷汗'],
  ['cry', '😢', '哭 cry'],
  ['sob', '😭', '大哭'],
  ['sleepy', '😪', '困'],
  ['sleeping', '😴', '睡觉'],
  ['mask', '😷', '口罩'],
  ['sunglasses', '😎', '酷 cool'],
  ['nerd_face', '🤓', '书呆子'],
  ['exploding_head', '🤯', '爆头'],
  ['cowboy_hat_face', '🤠', '牛仔'],
  ['partying_face', '🥳', '派对'],
  ['woozy_face', '🥴', '醉'],
  ['pleading_face', '🥺', '可怜'],
  ['rage', '😡', '生气'],
  ['angry', '😠', '愤怒'],
  ['triumph', '😤', '哼'],
  ['imp', '👿', '小恶魔'],
  ['skull', '💀', '骷髅'],
  ['ghost', '👻', '鬼'],
  ['alien', '👽', '外星人'],
  ['robot', '🤖', '机器人 robot'],
  ['poop', '💩', '便便'],
  ['clown_face', '🤡', '小丑'],
  // Hands & body
  ['+1', '👍', '赞 thumbs up'],
  ['-1', '👎', '踩 thumbs down'],
  ['ok_hand', '👌', 'ok'],
  ['punch', '👊', '拳头'],
  ['fist', '✊', '拳头 fist'],
  ['v', '✌️', '剪刀手 victory'],
  ['wave', '👋', '挥手'],
  ['raised_hands', '🙌', '欢呼'],
  ['pray', '🙏', '祈祷 thanks'],
  ['clap', '👏', '鼓掌'],
  ['point_right', '👉', '右指'],
  ['point_left', '👈', '左指'],
  ['point_up', '👆', '上指'],
  ['point_down', '👇', '下指'],
  ['muscle', '💪', '肌肉'],
  ['eyes', '👀', '眼睛'],
  ['brain', '🧠', '脑'],
  // Hearts
  ['heart', '❤️', '红心 heart'],
  ['blue_heart', '💙', '蓝心'],
  ['green_heart', '💚', '绿心'],
  ['yellow_heart', '💛', '黄心'],
  ['purple_heart', '💜', '紫心'],
  ['black_heart', '🖤', '黑心'],
  ['orange_heart', '🧡', '橙心'],
  ['white_heart', '🤍', '白心'],
  ['broken_heart', '💔', '碎心'],
  ['two_hearts', '💕', '双心'],
  ['sparkling_heart', '💖', '闪亮心'],
  // Symbols & UI markers
  ['fire', '🔥', '火 fire 热门'],
  ['sparkles', '✨', '闪光 sparkles'],
  ['star', '⭐', '星'],
  ['star2', '🌟', '亮星'],
  ['boom', '💥', '爆炸'],
  ['zap', '⚡', '闪电 zap fast'],
  ['bulb', '💡', '灵感 idea'],
  ['warning', '⚠️', '警告 warning'],
  ['no_entry', '⛔', '禁止'],
  ['no_entry_sign', '🚫', '禁止符'],
  ['white_check_mark', '✅', '完成 check done'],
  ['ballot_box_with_check', '☑️', '已选'],
  ['heavy_check_mark', '✔️', '勾'],
  ['x', '❌', '错 x error'],
  ['negative_squared_cross_mark', '❎', '叉框'],
  ['question', '❓', '问号'],
  ['grey_question', '❔', '灰问号'],
  ['exclamation', '❗', '感叹号'],
  ['heavy_exclamation_mark', '❕', '灰感叹'],
  ['bangbang', '‼️', '双感叹'],
  ['100', '💯', '满分 100'],
  ['ok', '🆗', 'ok 标记'],
  ['new', '🆕', '新 new'],
  ['cool', '🆒', 'cool'],
  ['top', '🔝', '置顶'],
  ['up', '🔼', '上'],
  ['down', '🔽', '下'],
  ['arrow_right', '➡️', '右箭头'],
  ['arrow_left', '⬅️', '左箭头'],
  ['arrow_up', '⬆️', '上箭头'],
  ['arrow_down', '⬇️', '下箭头'],
  ['arrow_forward', '▶️', '播放'],
  ['rewind', '⏪', '快退'],
  ['fast_forward', '⏩', '快进'],
  ['pause_button', '⏸️', '暂停'],
  ['stop_button', '⏹️', '停止'],
  // Objects / tech
  ['computer', '💻', '电脑 computer'],
  ['desktop_computer', '🖥️', '台式机 desktop'],
  ['keyboard', '⌨️', '键盘'],
  ['mouse_three_button', '🖱️', '鼠标'],
  ['printer', '🖨️', '打印机'],
  ['floppy_disk', '💾', '软盘 save'],
  ['minidisc', '💽', '光盘'],
  ['cd', '💿', 'cd'],
  ['dvd', '📀', 'dvd'],
  ['iphone', '📱', '手机 phone mobile'],
  ['calling', '📲', '来电'],
  ['phone', '☎️', '电话'],
  ['fax', '📠', '传真'],
  ['battery', '🔋', '电池'],
  ['electric_plug', '🔌', '插头'],
  ['joystick', '🕹️', '摇杆'],
  ['video_game', '🎮', '游戏手柄 game'],
  ['headphones', '🎧', '耳机'],
  ['microphone', '🎤', '麦克'],
  ['mag', '🔍', '放大 search'],
  ['mag_right', '🔎', '搜索'],
  ['lock', '🔒', '锁 lock'],
  ['unlock', '🔓', '解锁'],
  ['key', '🔑', '钥匙'],
  ['hammer', '🔨', '锤子'],
  ['wrench', '🔧', '扳手 config'],
  ['gear', '⚙️', '齿轮 settings'],
  ['link', '🔗', '链接'],
  ['paperclip', '📎', '回形针'],
  ['scissors', '✂️', '剪刀'],
  ['package', '📦', '包裹 package'],
  ['gift', '🎁', '礼物'],
  ['tada', '🎉', '庆祝 tada celebrate'],
  ['confetti_ball', '🎊', '彩球'],
  ['balloon', '🎈', '气球'],
  ['birthday', '🎂', '生日蛋糕'],
  // Books / paper
  ['book', '📖', '书 book'],
  ['books', '📚', '书堆 books docs'],
  ['notebook', '📓', '笔记本'],
  ['memo', '📝', '备忘 memo note'],
  ['pencil2', '✏️', '铅笔'],
  ['page_facing_up', '📄', '文档'],
  ['page_with_curl', '📃', '卷页'],
  ['scroll', '📜', '卷轴'],
  ['clipboard', '📋', '剪贴板'],
  ['bookmark', '🔖', '书签'],
  // Time
  ['hourglass', '⌛', '沙漏 进行中'],
  ['hourglass_flowing_sand', '⏳', '沙漏'],
  ['watch', '⌚', '手表'],
  ['alarm_clock', '⏰', '闹钟'],
  ['stopwatch', '⏱️', '秒表'],
  ['calendar', '📆', '日历'],
  ['date', '📅', '日期'],
  // Weather / nature
  ['sunny', '☀️', '晴天'],
  ['cloud', '☁️', '云'],
  ['partly_sunny', '⛅', '多云'],
  ['rainbow', '🌈', '彩虹'],
  ['snowflake', '❄️', '雪花'],
  ['umbrella', '☂️', '伞'],
  ['ocean', '🌊', '浪 wave'],
  // Misc useful
  ['rocket', '🚀', '火箭 rocket fast'],
  ['airplane', '✈️', '飞机'],
  ['ship', '🚢', '船'],
  ['car', '🚗', '车'],
  ['bike', '🚲', '自行车'],
  ['bug', '🐛', 'bug'],
  ['ant', '🐜', '蚂蚁'],
  ['spider', '🕷️', '蜘蛛'],
  ['rabbit', '🐰', '兔 rabbit'],
  ['rabbit2', '🐇', '兔子'],
  ['cat', '🐱', '猫 cat'],
  ['dog', '🐶', '狗 dog'],
  ['mouse', '🐭', '鼠'],
  ['hamster', '🐹', '仓鼠'],
  ['fox_face', '🦊', '狐狸'],
  ['bear', '🐻', '熊'],
  ['panda_face', '🐼', '熊猫'],
  ['tiger', '🐯', '虎'],
  ['lion_face', '🦁', '狮'],
  ['pig', '🐷', '猪'],
  ['cow', '🐮', '牛'],
  ['monkey_face', '🐵', '猴'],
  ['chicken', '🐔', '鸡'],
  ['penguin', '🐧', '企鹅'],
  ['fish', '🐟', '鱼'],
  ['turtle', '🐢', '龟'],
  ['dragon', '🐉', '龙'],
  ['unicorn_face', '🦄', '独角兽'],
  // Food
  ['coffee', '☕', '咖啡 coffee'],
  ['tea', '🍵', '茶'],
  ['beer', '🍺', '啤酒'],
  ['wine_glass', '🍷', '红酒'],
  ['cake', '🍰', '蛋糕'],
  ['cookie', '🍪', '饼干'],
  ['doughnut', '🍩', '甜甜圈'],
  ['hamburger', '🍔', '汉堡'],
  ['pizza', '🍕', '披萨'],
  ['ramen', '🍜', '拉面'],
  ['rice', '🍚', '饭'],
  ['sushi', '🍣', '寿司'],
  ['apple', '🍎', '苹果'],
  ['banana', '🍌', '香蕉'],
  ['watermelon', '🍉', '西瓜'],
]

export const EMOJI_LIST: EmojiEntry[] = RAW.map(([code, char, name]) => ({
  code: ':' + code + ':',
  char,
  name: name.toLowerCase(),
}))
